<script setup>
import AuthenticatedLayout from "@/Layouts/AuthenticatedLayout.vue";
import VetoModal from "@/Components/Vetos/VetoModal.vue";
import { Head, Link, router, usePage } from "@inertiajs/vue3";
import { TrashIcon } from "@heroicons/vue/20/solid";
import {
    Container,
    HH1,
    PrimaryButton,
    DangerButton,
    Card,
    CardTitle,
    pushModal,
    confirmDialog,
} from "@hjbdev/ui";
import { watch } from "vue";

defineOptions({ layout: AuthenticatedLayout });

const props = defineProps({
    series: Object,
    maps: Array,
});

function openVetoModal() {
    pushModal(VetoModal, {
        series: props.series,
        maps: props.maps,
        size: "large",
    });
}

if (usePage().props.flash?.veto && props.series.vetos.length < 7) {
    openVetoModal();
}

watch(
    () => props.series.vetos,
    (newVetos, oldVetos) => {
        if (newVetos.length < oldVetos.length) {
            return;
        }
        if (props.series.vetos.length < 7) {
            setTimeout(() => {
                openVetoModal()
            }, 200);
        }
    },
);

async function deleteVeto(id) {
    if (
        await confirmDialog(
            "Are you sure?",
            "Deleting this veto cannot be undone. If there are vetos in front of this veto, they must also be deleted if you are replacing this veto. If any series maps have been generated by this veto, they will need to be removed separately",
        )
    ) {
        router.delete(
            route("admin.series.vetos.destroy", {
                match: props.series.id,
                veto: id,
            }),
        );
    }
}

async function deleteSeriesMap(id) {
    if (
        await confirmDialog(
            "Are you sure?",
            "This cannot be undone. Data associated with this series map could be lost.",
        )
    ) {
        router.delete(
            route("admin.series.series-maps.destroy", {
                match: props.series.id,
                series_map: id,
            }),
        );
    }
}

const baseUrl = window.location.origin;
</script>

<template>
    <Head title="series" />

    <Container class="py-6 space-y-6">
        <div class="flex items-center justify-between mb-6">
            <HH1
                >Series {{ series.id }} - {{ series.team_a.name }} vs
                {{ series.team_b.name }} <small>{{ series.type }}</small></HH1
            >
            <div>
                <PrimaryButton
                    :as="Link"
                    :href="route('admin.series.edit', series.id)"
                    >Edit</PrimaryButton
                >
            </div>
        </div>

        <Card>
            <template #header>
                <CardTitle>Maps</CardTitle>
            </template>
            <template #extra>
                <PrimaryButton @click="openVetoModal">Veto</PrimaryButton>
            </template>
            <ul v-if="series.vetos?.length" class="mb-6">
                <li v-for="veto in series.vetos" class="flex gap-2">
                    {{ veto.team?.name }} {{ veto.type }} {{ veto.map.title }}
                    <DangerButton size="tiny" @click="deleteVeto(veto.id)"
                        ><TrashIcon class="h-4 w-4 pr-0.25"
                    /></DangerButton>
                </li>
            </ul>
            <div class="flex gap-6 flex-wrap">
                <div
                    v-for="seriesMap in series.series_maps"
                    class="relative overflow-hidden rounded-lg"
                >
                    <DangerButton
                        class="absolute top-3 right-3 z-10"
                        size="tiny"
                        @click="deleteSeriesMap(seriesMap.id)"
                    >
                        <TrashIcon class="w-5 h-5" />
                    </DangerButton>
                    <img
                        :src="`https://stratbox.app/images/maps/${seriesMap.map?.title?.toLowerCase()}_thumb.jpg`"
                        class="w-80"
                    />
                    <div
                        class="absolute inset-0 bg-gradient-to-t from-black to-transparent flex items-end p-6 text-lg justify-between"
                    >
                        <div>
                            {{ seriesMap.map.title }}:
                            {{ seriesMap.team_a_score }} -
                            {{ seriesMap.team_b_score }}
                        </div>
                        <div>
                            {{ seriesMap.status }}
                        </div>
                    </div>
                </div>
                <div v-if="!series.series_maps.length">No maps yet</div>
            </div>
        </Card>

        <Card>
            <template #header>
                <CardTitle>Command</CardTitle>
            </template>
            <code class="block"
                >logaddress_add_http "{{
                    baseUrl === "http://localhost"
                        ? "http://192.168.5.137"
                        : baseUrl
                }}/api/log-handler"</code
            >
        </Card>
    </Container>
</template>
